# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 15:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curp', models.CharField(max_length=200)),
                ('social_number', models.PositiveIntegerField()),
                ('rfc', models.PositiveIntegerField()),
                ('birthday', models.CharField(max_length=200)),
                ('hire_date', models.CharField(max_length=200)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Contracts')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
