# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 01:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contract',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Contracts'),
            preserve_default=False,
        ),
    ]
