# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-15 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Additional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DESCRIPTION', models.CharField(max_length=50)),
                ('IMAGE', models.ImageField(upload_to='clients/')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STREET_NAME', models.CharField(max_length=50)),
                ('NEIGHBORHOOD', models.CharField(max_length=50)),
                ('ZIP', models.CharField(max_length=50)),
                ('CITY', models.CharField(max_length=50)),
                ('STATE', models.CharField(max_length=50)),
                ('COUNTRY', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CONTACT_NAME_1', models.CharField(max_length=50)),
                ('PHONE_1', models.CharField(max_length=50)),
                ('MAIL_1', models.EmailField(max_length=50)),
                ('CONTACT_NAME_2', models.CharField(max_length=50)),
                ('PHONE_2', models.CharField(max_length=50)),
                ('MAIL_2', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COMPANY', models.CharField(max_length=50)),
                ('NAME', models.CharField(max_length=50)),
                ('RFC', models.CharField(max_length=50)),
                ('TYPE', models.CharField(max_length=50)),
                ('SOURCE', models.CharField(max_length=50)),
                ('PHONE', models.CharField(max_length=50)),
                ('DATE_1', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
