# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COMPANY', models.CharField(blank=True, max_length=50)),
                ('NAME', models.CharField(blank=True, max_length=50)),
                ('RFC', models.CharField(blank=True, max_length=50)),
                ('TYPE', models.CharField(blank=True, max_length=50)),
                ('SOURCE', models.CharField(blank=True, max_length=50)),
                ('PHONE', models.CharField(blank=True, max_length=50)),
                ('DATE_1', models.CharField(blank=True, max_length=50)),
                ('VENDOR', models.CharField(blank=True, max_length=50)),
                ('CONTACT_NAME_1', models.CharField(blank=True, max_length=50)),
                ('PHONE_1', models.CharField(blank=True, max_length=50)),
                ('EXT_1', models.CharField(blank=True, max_length=10)),
                ('MAIL_1', models.EmailField(blank=True, max_length=50)),
                ('CONTACT_NAME_2', models.CharField(blank=True, max_length=50)),
                ('PHONE_2', models.CharField(blank=True, max_length=50)),
                ('EXT_2', models.CharField(blank=True, max_length=10)),
                ('MAIL_2', models.EmailField(blank=True, max_length=50)),
                ('STREET_NAME', models.CharField(blank=True, max_length=50)),
                ('NEIGHBORHOOD', models.CharField(blank=True, max_length=50)),
                ('ZIP', models.CharField(blank=True, max_length=50)),
                ('CITY', models.CharField(blank=True, max_length=50)),
                ('STATE', models.CharField(blank=True, max_length=50)),
                ('COUNTRY', models.CharField(blank=True, max_length=50)),
                ('DESCRIPTION', models.CharField(blank=True, max_length=500)),
                ('IMAGE', models.ImageField(blank=True, upload_to='clients/')),
            ],
        ),
        migrations.CreateModel(
            name='Parks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IND_PARK', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('IND_PARK',),
            },
        ),
        migrations.AddField(
            model_name='clients',
            name='IND_PARK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Parks'),
        ),
    ]
